name: date_field
description: A widget in the form of a field that lets people choose a date, a time or both.
version: 4.0.1
homepage: 'https://github.com/dyu/date_field'

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
